namespace Speedway.Mach1;

public enum INVALID_CMD_REASON_CODE
{
	INVALID_CATEGORY,
	INVALID_CRC,
	INVALID_MID,
	INVALID_OTHER_HEADER,
	INVALID_MODEM_STATE,
	PARAMS_OUT_RANGE,
	MISSING_CMD_PARAMS,
	INVALID_OPT_PARAM_ID,
	OTHER_PARAM_ERR,
	OUT_OF_SYNC,
	CMD_IN_PROGRESS
}
