using System.ComponentModel;

namespace Microsoft.SqlServer.Management.Smo;

[TypeConverter(typeof(AuditActionTypeConverter))]
public enum AuditActionType
{
	[TsqlSyntaxString("APPLICATION_ROLE_CHANGE_PASSWORD_GROUP")]
	ApplicationRoleChangePasswordGroup,
	[TsqlSyntaxString("AUDIT_CHANGE_GROUP")]
	AuditChangeGroup,
	[TsqlSyntaxString("BACKUP_RESTORE_GROUP")]
	BackupRestoreGroup,
	[TsqlSyntaxString("BATCH_COMPLETED_GROUP")]
	BatchCompletedGroup,
	[TsqlSyntaxString("BATCH_STARTED_GROUP")]
	BatchStartedGroup,
	[TsqlSyntaxString("BROKER_LOGIN_GROUP")]
	BrokerLoginGroup,
	[TsqlSyntaxString("DATABASE_CHANGE_GROUP")]
	DatabaseChangeGroup,
	[TsqlSyntaxString("DATABASE_LOGOUT_GROUP")]
	DatabaseLogoutGroup,
	[TsqlSyntaxString("DATABASE_MIRRORING_LOGIN_GROUP")]
	DatabaseMirroringLoginGroup,
	[TsqlSyntaxString("DATABASE_OBJECT_ACCESS_GROUP")]
	DatabaseObjectAccessGroup,
	[TsqlSyntaxString("DATABASE_OBJECT_CHANGE_GROUP")]
	DatabaseObjectChangeGroup,
	[TsqlSyntaxString("DATABASE_OBJECT_OWNERSHIP_CHANGE_GROUP")]
	DatabaseObjectOwnershipChangeGroup,
	[TsqlSyntaxString("DATABASE_OBJECT_PERMISSION_CHANGE_GROUP")]
	DatabaseObjectPermissionChangeGroup,
	[TsqlSyntaxString("DATABASE_OPERATION_GROUP")]
	DatabaseOperationGroup,
	[TsqlSyntaxString("DATABASE_OWNERSHIP_CHANGE_GROUP")]
	DatabaseOwnershipChangeGroup,
	[TsqlSyntaxString("DATABASE_PERMISSION_CHANGE_GROUP")]
	DatabasePermissionChangeGroup,
	[TsqlSyntaxString("DATABASE_PRINCIPAL_CHANGE_GROUP")]
	DatabasePrincipalChangeGroup,
	[TsqlSyntaxString("DATABASE_PRINCIPAL_IMPERSONATION_GROUP")]
	DatabasePrincipalImpersonationGroup,
	[TsqlSyntaxString("DATABASE_ROLE_MEMBER_CHANGE_GROUP")]
	DatabaseRoleMemberChangeGroup,
	[TsqlSyntaxString("DBCC_GROUP")]
	DbccGroup,
	[TsqlSyntaxString("DELETE")]
	Delete,
	[TsqlSyntaxString("EXECUTE")]
	Execute,
	[TsqlSyntaxString("FAILED_DATABASE_AUTHENTICATION_GROUP")]
	FailedDatabaseAuthenticationGroup,
	[TsqlSyntaxString("FAILED_LOGIN_GROUP")]
	FailedLoginGroup,
	[TsqlSyntaxString("FULLTEXT_GROUP")]
	FullTextGroup,
	[TsqlSyntaxString("GLOBAL_TRANSACTIONS_LOGIN_GROUP")]
	GlobalTransactionsLoginGroup,
	[TsqlSyntaxString("INSERT")]
	Insert,
	[TsqlSyntaxString("LOGIN_CHANGE_PASSWORD_GROUP")]
	LoginChangePasswordGroup,
	[TsqlSyntaxString("LOGOUT_GROUP")]
	LogoutGroup,
	[TsqlSyntaxString("RECEIVE")]
	Receive,
	[TsqlSyntaxString("REFERENCES")]
	References,
	[TsqlSyntaxString("SCHEMA_OBJECT_ACCESS_GROUP")]
	SchemaObjectAccessGroup,
	[TsqlSyntaxString("SCHEMA_OBJECT_CHANGE_GROUP")]
	SchemaObjectChangeGroup,
	[TsqlSyntaxString("SCHEMA_OBJECT_OWNERSHIP_CHANGE_GROUP")]
	SchemaObjectOwnershipChangeGroup,
	[TsqlSyntaxString("SCHEMA_OBJECT_PERMISSION_CHANGE_GROUP")]
	SchemaObjectPermissionChangeGroup,
	[TsqlSyntaxString("SELECT")]
	Select,
	[TsqlSyntaxString("SERVER_OBJECT_CHANGE_GROUP")]
	ServerObjectChangeGroup,
	[TsqlSyntaxString("SERVER_OBJECT_OWNERSHIP_CHANGE_GROUP")]
	ServerObjectOwnershipChangeGroup,
	[TsqlSyntaxString("SERVER_OBJECT_PERMISSION_CHANGE_GROUP")]
	ServerObjectPermissionChangeGroup,
	[TsqlSyntaxString("SERVER_OPERATION_GROUP")]
	ServerOperationGroup,
	[TsqlSyntaxString("SERVER_PERMIS")]
	ServerPermissionChangeGroup,
	[TsqlSyntaxString("SERVER_PRINCIPAL_CHANGE_GROUP")]
	ServerPrincipalChangeGroup,
	[TsqlSyntaxString("SERVER_PRINCIPAL_IMPERSONATION_GROUP")]
	ServerPrincipalImpersonationGroup,
	[TsqlSyntaxString("SERVER_ROLE_MEMBER_CHANGE_GROUP")]
	ServerRoleMemberChangeGroup,
	[TsqlSyntaxString("SERVER_STATE_CHANGE_GROUP")]
	ServerStateChangeGroup,
	[TsqlSyntaxString("SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP")]
	SuccessfulDatabaseAuthenticationGroup,
	[TsqlSyntaxString("SUCCESSFUL_LOGIN_GROUP")]
	SuccessfulLoginGroup,
	[TsqlSyntaxString("TRACE_CHANGE_GROUP")]
	TraceChangeGroup,
	[TsqlSyntaxString("UPDATE")]
	Update,
	[TsqlSyntaxString("USER_CHANGE_PASSWORD_GROUP")]
	UserChangePasswordGroup,
	[TsqlSyntaxString("USER_DEFINED_AUDIT_GROUP")]
	UserDefinedAuditGroup,
	[TsqlSyntaxString("TRANSACTION_GROUP")]
	TransactionGroup
}
