using System;
using System.Data;

namespace Microsoft.SqlServer.Management.Smo;

internal class PostProcessDatabaseDdlTriggerEvents : PostProcessDdlEvents
{
	protected override object GetTriggerEvents(string objectIdentifier)
	{
		DataTable eventsForAllRows = GetEventsForAllRows();
		int num = BinarySearchSetOnFirst(eventsForAllRows.Rows, objectIdentifier, "ObjectIdentifier");
		if (0 > num)
		{
			return DBNull.Value;
		}
		DatabaseDdlTriggerEventSet databaseDdlTriggerEventSet = new DatabaseDdlTriggerEventSet();
		do
		{
			DatabaseDdlTriggerEvent databaseDdlTriggerEvent = DatabaseDdlTriggerEventOffsetFromEventString(eventsForAllRows.Rows[num]["EventTypeDescription"].ToString());
			databaseDdlTriggerEventSet.SetBitAt((int)databaseDdlTriggerEvent.Value, value: true);
		}
		while (++num < eventsForAllRows.Rows.Count && objectIdentifier == eventsForAllRows.Rows[num]["ObjectIdentifier"].ToString());
		return databaseDdlTriggerEventSet;
	}

	private DatabaseDdlTriggerEvent DatabaseDdlTriggerEventOffsetFromEventString(string evtdesc)
	{
		return evtdesc switch
		{
			"ADD_ROLE_MEMBER" => DatabaseDdlTriggerEvent.AddRoleMember, 
			"ADD_SENSITIVITY_CLASSIFICATION" => DatabaseDdlTriggerEvent.AddSensitivityClassification, 
			"ADD_SIGNATURE" => DatabaseDdlTriggerEvent.AddSignature, 
			"ADD_SIGNATURE_SCHEMA_OBJECT" => DatabaseDdlTriggerEvent.AddSignatureSchemaObject, 
			"ALTER_APPLICATION_ROLE" => DatabaseDdlTriggerEvent.AlterApplicationRole, 
			"ALTER_ASSEMBLY" => DatabaseDdlTriggerEvent.AlterAssembly, 
			"ALTER_ASYMMETRIC_KEY" => DatabaseDdlTriggerEvent.AlterAsymmetricKey, 
			"ALTER_AUDIT" => DatabaseDdlTriggerEvent.AlterAudit, 
			"ALTER_AUTHORIZATION_DATABASE" => DatabaseDdlTriggerEvent.AlterAuthorizationDatabase, 
			"ALTER_BROKER_PRIORITY" => DatabaseDdlTriggerEvent.AlterBrokerPriority, 
			"ALTER_CERTIFICATE" => DatabaseDdlTriggerEvent.AlterCertificate, 
			"ALTER_COLUMN_ENCRYPTION_KEY" => DatabaseDdlTriggerEvent.AlterColumnEncryptionKey, 
			"ALTER_DATABASE_AUDIT_SPECIFICATION" => DatabaseDdlTriggerEvent.AlterDatabaseAuditSpecification, 
			"ALTER_DATABASE_ENCRYPTION_KEY" => DatabaseDdlTriggerEvent.AlterDatabaseEncryptionKey, 
			"ALTER_DATABASE_SCOPED_CONFIGURATION" => DatabaseDdlTriggerEvent.AlterDatabaseScopedConfiguration, 
			"ALTER_EXTENDED_PROPERTY" => DatabaseDdlTriggerEvent.AlterExtendedProperty, 
			"ALTER_EXTERNAL_LIBRARY" => DatabaseDdlTriggerEvent.AlterExternalLibrary, 
			"ALTER_FULLTEXT_CATALOG" => DatabaseDdlTriggerEvent.AlterFulltextCatalog, 
			"ALTER_FULLTEXT_INDEX" => DatabaseDdlTriggerEvent.AlterFulltextIndex, 
			"ALTER_FULLTEXT_STOPLIST" => DatabaseDdlTriggerEvent.AlterFulltextStoplist, 
			"ALTER_FUNCTION" => DatabaseDdlTriggerEvent.AlterFunction, 
			"ALTER_INDEX" => DatabaseDdlTriggerEvent.AlterIndex, 
			"ALTER_MASTER_KEY" => DatabaseDdlTriggerEvent.AlterMasterKey, 
			"ALTER_MESSAGE_TYPE" => DatabaseDdlTriggerEvent.AlterMessageType, 
			"ALTER_PARTITION_FUNCTION" => DatabaseDdlTriggerEvent.AlterPartitionFunction, 
			"ALTER_PARTITION_SCHEME" => DatabaseDdlTriggerEvent.AlterPartitionScheme, 
			"ALTER_PLAN_GUIDE" => DatabaseDdlTriggerEvent.AlterPlanGuide, 
			"ALTER_PROCEDURE" => DatabaseDdlTriggerEvent.AlterProcedure, 
			"ALTER_QUEUE" => DatabaseDdlTriggerEvent.AlterQueue, 
			"ALTER_REMOTE_SERVICE_BINDING" => DatabaseDdlTriggerEvent.AlterRemoteServiceBinding, 
			"ALTER_ROLE" => DatabaseDdlTriggerEvent.AlterRole, 
			"ALTER_ROUTE" => DatabaseDdlTriggerEvent.AlterRoute, 
			"ALTER_SCHEMA" => DatabaseDdlTriggerEvent.AlterSchema, 
			"ALTER_SEARCH_PROPERTY_LIST" => DatabaseDdlTriggerEvent.AlterSearchPropertyList, 
			"ALTER_SECURITY_POLICY" => DatabaseDdlTriggerEvent.AlterSecurityPolicy, 
			"ALTER_SEQUENCE" => DatabaseDdlTriggerEvent.AlterSequence, 
			"ALTER_SERVICE" => DatabaseDdlTriggerEvent.AlterService, 
			"ALTER_SYMMETRIC_KEY" => DatabaseDdlTriggerEvent.AlterSymmetricKey, 
			"ALTER_TABLE" => DatabaseDdlTriggerEvent.AlterTable, 
			"ALTER_TRIGGER" => DatabaseDdlTriggerEvent.AlterTrigger, 
			"ALTER_USER" => DatabaseDdlTriggerEvent.AlterUser, 
			"ALTER_VIEW" => DatabaseDdlTriggerEvent.AlterView, 
			"ALTER_XML_SCHEMA_COLLECTION" => DatabaseDdlTriggerEvent.AlterXmlSchemaCollection, 
			"BIND_DEFAULT" => DatabaseDdlTriggerEvent.BindDefault, 
			"BIND_RULE" => DatabaseDdlTriggerEvent.BindRule, 
			"CREATE_APPLICATION_ROLE" => DatabaseDdlTriggerEvent.CreateApplicationRole, 
			"CREATE_ASSEMBLY" => DatabaseDdlTriggerEvent.CreateAssembly, 
			"CREATE_ASYMMETRIC_KEY" => DatabaseDdlTriggerEvent.CreateAsymmetricKey, 
			"CREATE_AUDIT" => DatabaseDdlTriggerEvent.CreateAudit, 
			"CREATE_BROKER_PRIORITY" => DatabaseDdlTriggerEvent.CreateBrokerPriority, 
			"CREATE_CERTIFICATE" => DatabaseDdlTriggerEvent.CreateCertificate, 
			"CREATE_COLUMN_ENCRYPTION_KEY" => DatabaseDdlTriggerEvent.CreateColumnEncryptionKey, 
			"CREATE_COLUMN_MASTER_KEY" => DatabaseDdlTriggerEvent.CreateColumnMasterKey, 
			"CREATE_CONTRACT" => DatabaseDdlTriggerEvent.CreateContract, 
			"CREATE_DATABASE_AUDIT_SPECIFICATION" => DatabaseDdlTriggerEvent.CreateDatabaseAuditSpecification, 
			"CREATE_DATABASE_ENCRYPTION_KEY" => DatabaseDdlTriggerEvent.CreateDatabaseEncryptionKey, 
			"CREATE_DEFAULT" => DatabaseDdlTriggerEvent.CreateDefault, 
			"CREATE_EVENT_NOTIFICATION" => DatabaseDdlTriggerEvent.CreateEventNotification, 
			"CREATE_EXTENDED_PROPERTY" => DatabaseDdlTriggerEvent.CreateExtendedProperty, 
			"CREATE_EXTERNAL_LIBRARY" => DatabaseDdlTriggerEvent.CreateExternalLibrary, 
			"CREATE_FULLTEXT_CATALOG" => DatabaseDdlTriggerEvent.CreateFulltextCatalog, 
			"CREATE_FULLTEXT_INDEX" => DatabaseDdlTriggerEvent.CreateFulltextIndex, 
			"CREATE_FULLTEXT_STOPLIST" => DatabaseDdlTriggerEvent.CreateFulltextStoplist, 
			"CREATE_FUNCTION" => DatabaseDdlTriggerEvent.CreateFunction, 
			"CREATE_INDEX" => DatabaseDdlTriggerEvent.CreateIndex, 
			"CREATE_MASTER_KEY" => DatabaseDdlTriggerEvent.CreateMasterKey, 
			"CREATE_MESSAGE_TYPE" => DatabaseDdlTriggerEvent.CreateMessageType, 
			"CREATE_PARTITION_FUNCTION" => DatabaseDdlTriggerEvent.CreatePartitionFunction, 
			"CREATE_PARTITION_SCHEME" => DatabaseDdlTriggerEvent.CreatePartitionScheme, 
			"CREATE_PLAN_GUIDE" => DatabaseDdlTriggerEvent.CreatePlanGuide, 
			"CREATE_PROCEDURE" => DatabaseDdlTriggerEvent.CreateProcedure, 
			"CREATE_QUEUE" => DatabaseDdlTriggerEvent.CreateQueue, 
			"CREATE_REMOTE_SERVICE_BINDING" => DatabaseDdlTriggerEvent.CreateRemoteServiceBinding, 
			"CREATE_ROLE" => DatabaseDdlTriggerEvent.CreateRole, 
			"CREATE_ROUTE" => DatabaseDdlTriggerEvent.CreateRoute, 
			"CREATE_RULE" => DatabaseDdlTriggerEvent.CreateRule, 
			"CREATE_SCHEMA" => DatabaseDdlTriggerEvent.CreateSchema, 
			"CREATE_SEARCH_PROPERTY_LIST" => DatabaseDdlTriggerEvent.CreateSearchPropertyList, 
			"CREATE_SECURITY_POLICY" => DatabaseDdlTriggerEvent.CreateSecurityPolicy, 
			"CREATE_SEQUENCE" => DatabaseDdlTriggerEvent.CreateSequence, 
			"CREATE_SERVICE" => DatabaseDdlTriggerEvent.CreateService, 
			"CREATE_SPATIAL_INDEX" => DatabaseDdlTriggerEvent.CreateSpatialIndex, 
			"CREATE_STATISTICS" => DatabaseDdlTriggerEvent.CreateStatistics, 
			"CREATE_SYMMETRIC_KEY" => DatabaseDdlTriggerEvent.CreateSymmetricKey, 
			"CREATE_SYNONYM" => DatabaseDdlTriggerEvent.CreateSynonym, 
			"CREATE_TABLE" => DatabaseDdlTriggerEvent.CreateTable, 
			"CREATE_TRIGGER" => DatabaseDdlTriggerEvent.CreateTrigger, 
			"CREATE_TYPE" => DatabaseDdlTriggerEvent.CreateType, 
			"CREATE_USER" => DatabaseDdlTriggerEvent.CreateUser, 
			"CREATE_VIEW" => DatabaseDdlTriggerEvent.CreateView, 
			"CREATE_XML_INDEX" => DatabaseDdlTriggerEvent.CreateXmlIndex, 
			"CREATE_XML_SCHEMA_COLLECTION" => DatabaseDdlTriggerEvent.CreateXmlSchemaCollection, 
			"DENY_DATABASE" => DatabaseDdlTriggerEvent.DenyDatabase, 
			"DROP_APPLICATION_ROLE" => DatabaseDdlTriggerEvent.DropApplicationRole, 
			"DROP_ASSEMBLY" => DatabaseDdlTriggerEvent.DropAssembly, 
			"DROP_ASYMMETRIC_KEY" => DatabaseDdlTriggerEvent.DropAsymmetricKey, 
			"DROP_AUDIT" => DatabaseDdlTriggerEvent.DropAudit, 
			"DROP_BROKER_PRIORITY" => DatabaseDdlTriggerEvent.DropBrokerPriority, 
			"DROP_CERTIFICATE" => DatabaseDdlTriggerEvent.DropCertificate, 
			"DROP_COLUMN_ENCRYPTION_KEY" => DatabaseDdlTriggerEvent.DropColumnEncryptionKey, 
			"DROP_COLUMN_MASTER_KEY" => DatabaseDdlTriggerEvent.DropColumnMasterKey, 
			"DROP_CONTRACT" => DatabaseDdlTriggerEvent.DropContract, 
			"DROP_DATABASE_AUDIT_SPECIFICATION" => DatabaseDdlTriggerEvent.DropDatabaseAuditSpecification, 
			"DROP_DATABASE_ENCRYPTION_KEY" => DatabaseDdlTriggerEvent.DropDatabaseEncryptionKey, 
			"DROP_DEFAULT" => DatabaseDdlTriggerEvent.DropDefault, 
			"DROP_EVENT_NOTIFICATION" => DatabaseDdlTriggerEvent.DropEventNotification, 
			"DROP_EXTENDED_PROPERTY" => DatabaseDdlTriggerEvent.DropExtendedProperty, 
			"DROP_EXTERNAL_LIBRARY" => DatabaseDdlTriggerEvent.DropExternalLibrary, 
			"DROP_FULLTEXT_CATALOG" => DatabaseDdlTriggerEvent.DropFulltextCatalog, 
			"DROP_FULLTEXT_INDEX" => DatabaseDdlTriggerEvent.DropFulltextIndex, 
			"DROP_FULLTEXT_STOPLIST" => DatabaseDdlTriggerEvent.DropFulltextStoplist, 
			"DROP_FUNCTION" => DatabaseDdlTriggerEvent.DropFunction, 
			"DROP_INDEX" => DatabaseDdlTriggerEvent.DropIndex, 
			"DROP_MASTER_KEY" => DatabaseDdlTriggerEvent.DropMasterKey, 
			"DROP_MESSAGE_TYPE" => DatabaseDdlTriggerEvent.DropMessageType, 
			"DROP_PARTITION_FUNCTION" => DatabaseDdlTriggerEvent.DropPartitionFunction, 
			"DROP_PARTITION_SCHEME" => DatabaseDdlTriggerEvent.DropPartitionScheme, 
			"DROP_PLAN_GUIDE" => DatabaseDdlTriggerEvent.DropPlanGuide, 
			"DROP_PROCEDURE" => DatabaseDdlTriggerEvent.DropProcedure, 
			"DROP_QUEUE" => DatabaseDdlTriggerEvent.DropQueue, 
			"DROP_REMOTE_SERVICE_BINDING" => DatabaseDdlTriggerEvent.DropRemoteServiceBinding, 
			"DROP_ROLE" => DatabaseDdlTriggerEvent.DropRole, 
			"DROP_ROLE_MEMBER" => DatabaseDdlTriggerEvent.DropRoleMember, 
			"DROP_ROUTE" => DatabaseDdlTriggerEvent.DropRoute, 
			"DROP_RULE" => DatabaseDdlTriggerEvent.DropRule, 
			"DROP_SCHEMA" => DatabaseDdlTriggerEvent.DropSchema, 
			"DROP_SEARCH_PROPERTY_LIST" => DatabaseDdlTriggerEvent.DropSearchPropertyList, 
			"DROP_SECURITY_POLICY" => DatabaseDdlTriggerEvent.DropSecurityPolicy, 
			"DROP_SENSITIVITY_CLASSIFICATION" => DatabaseDdlTriggerEvent.DropSensitivityClassification, 
			"DROP_SEQUENCE" => DatabaseDdlTriggerEvent.DropSequence, 
			"DROP_SERVICE" => DatabaseDdlTriggerEvent.DropService, 
			"DROP_SIGNATURE" => DatabaseDdlTriggerEvent.DropSignature, 
			"DROP_SIGNATURE_SCHEMA_OBJECT" => DatabaseDdlTriggerEvent.DropSignatureSchemaObject, 
			"DROP_STATISTICS" => DatabaseDdlTriggerEvent.DropStatistics, 
			"DROP_SYMMETRIC_KEY" => DatabaseDdlTriggerEvent.DropSymmetricKey, 
			"DROP_SYNONYM" => DatabaseDdlTriggerEvent.DropSynonym, 
			"DROP_TABLE" => DatabaseDdlTriggerEvent.DropTable, 
			"DROP_TRIGGER" => DatabaseDdlTriggerEvent.DropTrigger, 
			"DROP_TYPE" => DatabaseDdlTriggerEvent.DropType, 
			"DROP_USER" => DatabaseDdlTriggerEvent.DropUser, 
			"DROP_VIEW" => DatabaseDdlTriggerEvent.DropView, 
			"DROP_XML_SCHEMA_COLLECTION" => DatabaseDdlTriggerEvent.DropXmlSchemaCollection, 
			"GRANT_DATABASE" => DatabaseDdlTriggerEvent.GrantDatabase, 
			"RENAME" => DatabaseDdlTriggerEvent.Rename, 
			"REVOKE_DATABASE" => DatabaseDdlTriggerEvent.RevokeDatabase, 
			"UNBIND_DEFAULT" => DatabaseDdlTriggerEvent.UnbindDefault, 
			"UNBIND_RULE" => DatabaseDdlTriggerEvent.UnbindRule, 
			"UPDATE_STATISTICS" => DatabaseDdlTriggerEvent.UpdateStatistics, 
			_ => DatabaseDdlTriggerEvent.CreateTable, 
		};
	}
}
