using System;
using System.Data;

namespace Microsoft.SqlServer.Management.Smo;

internal class PostProcessServerDdlTriggerEvents : PostProcessDdlEvents
{
	protected override object GetTriggerEvents(string objectIdentifier)
	{
		DataTable eventsForAllRows = GetEventsForAllRows();
		int num = BinarySearchSetOnFirst(eventsForAllRows.Rows, objectIdentifier, "ObjectIdentifier");
		if (0 > num)
		{
			return DBNull.Value;
		}
		ServerDdlTriggerEventSet serverDdlTriggerEventSet = new ServerDdlTriggerEventSet();
		do
		{
			ServerDdlTriggerEvent serverDdlTriggerEvent = ServerDdlTriggerEventOffsetFromEventString(eventsForAllRows.Rows[num]["EventTypeDescription"].ToString());
			serverDdlTriggerEventSet.SetBitAt((int)serverDdlTriggerEvent.Value, value: true);
		}
		while (++num < eventsForAllRows.Rows.Count && objectIdentifier == eventsForAllRows.Rows[num]["ObjectIdentifier"].ToString());
		return serverDdlTriggerEventSet;
	}

	private ServerDdlTriggerEvent ServerDdlTriggerEventOffsetFromEventString(string evtdesc)
	{
		return evtdesc switch
		{
			"ADD_ROLE_MEMBER" => ServerDdlTriggerEvent.AddRoleMember, 
			"ADD_SENSITIVITY_CLASSIFICATION" => ServerDdlTriggerEvent.AddSensitivityClassification, 
			"ADD_SERVER_ROLE_MEMBER" => ServerDdlTriggerEvent.AddServerRoleMember, 
			"ADD_SIGNATURE" => ServerDdlTriggerEvent.AddSignature, 
			"ADD_SIGNATURE_SCHEMA_OBJECT" => ServerDdlTriggerEvent.AddSignatureSchemaObject, 
			"ALTER_APPLICATION_ROLE" => ServerDdlTriggerEvent.AlterApplicationRole, 
			"ALTER_ASSEMBLY" => ServerDdlTriggerEvent.AlterAssembly, 
			"ALTER_ASYMMETRIC_KEY" => ServerDdlTriggerEvent.AlterAsymmetricKey, 
			"ALTER_AUDIT" => ServerDdlTriggerEvent.AlterAudit, 
			"ALTER_AUTHORIZATION_DATABASE" => ServerDdlTriggerEvent.AlterAuthorizationDatabase, 
			"ALTER_AUTHORIZATION_SERVER" => ServerDdlTriggerEvent.AlterAuthorizationServer, 
			"ALTER_AVAILABILITY_GROUP" => ServerDdlTriggerEvent.AlterAvailabilityGroup, 
			"ALTER_BROKER_PRIORITY" => ServerDdlTriggerEvent.AlterBrokerPriority, 
			"ALTER_CERTIFICATE" => ServerDdlTriggerEvent.AlterCertificate, 
			"ALTER_COLUMN_ENCRYPTION_KEY" => ServerDdlTriggerEvent.AlterColumnEncryptionKey, 
			"ALTER_CREDENTIAL" => ServerDdlTriggerEvent.AlterCredential, 
			"ALTER_CRYPTOGRAPHIC_PROVIDER" => ServerDdlTriggerEvent.AlterCryptographicProvider, 
			"ALTER_DATABASE" => ServerDdlTriggerEvent.AlterDatabase, 
			"ALTER_DATABASE_AUDIT_SPECIFICATION" => ServerDdlTriggerEvent.AlterDatabaseAuditSpecification, 
			"ALTER_DATABASE_ENCRYPTION_KEY" => ServerDdlTriggerEvent.AlterDatabaseEncryptionKey, 
			"ALTER_DATABASE_SCOPED_CONFIGURATION" => ServerDdlTriggerEvent.AlterDatabaseScopedConfiguration, 
			"ALTER_ENDPOINT" => ServerDdlTriggerEvent.AlterEndpoint, 
			"ALTER_EVENT_SESSION" => ServerDdlTriggerEvent.AlterEventSession, 
			"ALTER_EXTENDED_PROPERTY" => ServerDdlTriggerEvent.AlterExtendedProperty, 
			"ALTER_EXTERNAL_LIBRARY" => ServerDdlTriggerEvent.AlterExternalLibrary, 
			"ALTER_EXTERNAL_RESOURCE_POOL" => ServerDdlTriggerEvent.AlterExternalResourcePool, 
			"ALTER_FULLTEXT_CATALOG" => ServerDdlTriggerEvent.AlterFulltextCatalog, 
			"ALTER_FULLTEXT_INDEX" => ServerDdlTriggerEvent.AlterFulltextIndex, 
			"ALTER_FULLTEXT_STOPLIST" => ServerDdlTriggerEvent.AlterFulltextStoplist, 
			"ALTER_FUNCTION" => ServerDdlTriggerEvent.AlterFunction, 
			"ALTER_INDEX" => ServerDdlTriggerEvent.AlterIndex, 
			"ALTER_INSTANCE" => ServerDdlTriggerEvent.AlterInstance, 
			"ALTER_LINKED_SERVER" => ServerDdlTriggerEvent.AlterLinkedServer, 
			"ALTER_LOGIN" => ServerDdlTriggerEvent.AlterLogin, 
			"ALTER_MASTER_KEY" => ServerDdlTriggerEvent.AlterMasterKey, 
			"ALTER_MESSAGE" => ServerDdlTriggerEvent.AlterMessage, 
			"ALTER_MESSAGE_TYPE" => ServerDdlTriggerEvent.AlterMessageType, 
			"ALTER_PARTITION_FUNCTION" => ServerDdlTriggerEvent.AlterPartitionFunction, 
			"ALTER_PARTITION_SCHEME" => ServerDdlTriggerEvent.AlterPartitionScheme, 
			"ALTER_PLAN_GUIDE" => ServerDdlTriggerEvent.AlterPlanGuide, 
			"ALTER_PROCEDURE" => ServerDdlTriggerEvent.AlterProcedure, 
			"ALTER_QUEUE" => ServerDdlTriggerEvent.AlterQueue, 
			"ALTER_REMOTE_SERVER" => ServerDdlTriggerEvent.AlterRemoteServer, 
			"ALTER_REMOTE_SERVICE_BINDING" => ServerDdlTriggerEvent.AlterRemoteServiceBinding, 
			"ALTER_RESOURCE_GOVERNOR_CONFIG" => ServerDdlTriggerEvent.AlterResourceGovernorConfig, 
			"ALTER_RESOURCE_POOL" => ServerDdlTriggerEvent.AlterResourcePool, 
			"ALTER_ROLE" => ServerDdlTriggerEvent.AlterRole, 
			"ALTER_ROUTE" => ServerDdlTriggerEvent.AlterRoute, 
			"ALTER_SCHEMA" => ServerDdlTriggerEvent.AlterSchema, 
			"ALTER_SEARCH_PROPERTY_LIST" => ServerDdlTriggerEvent.AlterSearchPropertyList, 
			"ALTER_SECURITY_POLICY" => ServerDdlTriggerEvent.AlterSecurityPolicy, 
			"ALTER_SEQUENCE" => ServerDdlTriggerEvent.AlterSequence, 
			"ALTER_SERVER_AUDIT" => ServerDdlTriggerEvent.AlterServerAudit, 
			"ALTER_SERVER_AUDIT_SPECIFICATION" => ServerDdlTriggerEvent.AlterServerAuditSpecification, 
			"ALTER_SERVER_ROLE" => ServerDdlTriggerEvent.AlterServerRole, 
			"ALTER_SERVICE" => ServerDdlTriggerEvent.AlterService, 
			"ALTER_SERVICE_MASTER_KEY" => ServerDdlTriggerEvent.AlterServiceMasterKey, 
			"ALTER_SYMMETRIC_KEY" => ServerDdlTriggerEvent.AlterSymmetricKey, 
			"ALTER_TABLE" => ServerDdlTriggerEvent.AlterTable, 
			"ALTER_TRIGGER" => ServerDdlTriggerEvent.AlterTrigger, 
			"ALTER_USER" => ServerDdlTriggerEvent.AlterUser, 
			"ALTER_VIEW" => ServerDdlTriggerEvent.AlterView, 
			"ALTER_WORKLOAD_GROUP" => ServerDdlTriggerEvent.AlterWorkloadGroup, 
			"ALTER_XML_SCHEMA_COLLECTION" => ServerDdlTriggerEvent.AlterXmlSchemaCollection, 
			"BIND_DEFAULT" => ServerDdlTriggerEvent.BindDefault, 
			"BIND_RULE" => ServerDdlTriggerEvent.BindRule, 
			"CREATE_APPLICATION_ROLE" => ServerDdlTriggerEvent.CreateApplicationRole, 
			"CREATE_ASSEMBLY" => ServerDdlTriggerEvent.CreateAssembly, 
			"CREATE_ASYMMETRIC_KEY" => ServerDdlTriggerEvent.CreateAsymmetricKey, 
			"CREATE_AUDIT" => ServerDdlTriggerEvent.CreateAudit, 
			"CREATE_AVAILABILITY_GROUP" => ServerDdlTriggerEvent.CreateAvailabilityGroup, 
			"CREATE_BROKER_PRIORITY" => ServerDdlTriggerEvent.CreateBrokerPriority, 
			"CREATE_CERTIFICATE" => ServerDdlTriggerEvent.CreateCertificate, 
			"CREATE_COLUMN_ENCRYPTION_KEY" => ServerDdlTriggerEvent.CreateColumnEncryptionKey, 
			"CREATE_COLUMN_MASTER_KEY" => ServerDdlTriggerEvent.CreateColumnMasterKey, 
			"CREATE_CONTRACT" => ServerDdlTriggerEvent.CreateContract, 
			"CREATE_CREDENTIAL" => ServerDdlTriggerEvent.CreateCredential, 
			"CREATE_CRYPTOGRAPHIC_PROVIDER" => ServerDdlTriggerEvent.CreateCryptographicProvider, 
			"CREATE_DATABASE" => ServerDdlTriggerEvent.CreateDatabase, 
			"CREATE_DATABASE_AUDIT_SPECIFICATION" => ServerDdlTriggerEvent.CreateDatabaseAuditSpecification, 
			"CREATE_DATABASE_ENCRYPTION_KEY" => ServerDdlTriggerEvent.CreateDatabaseEncryptionKey, 
			"CREATE_DEFAULT" => ServerDdlTriggerEvent.CreateDefault, 
			"CREATE_ENDPOINT" => ServerDdlTriggerEvent.CreateEndpoint, 
			"CREATE_EVENT_NOTIFICATION" => ServerDdlTriggerEvent.CreateEventNotification, 
			"CREATE_EVENT_SESSION" => ServerDdlTriggerEvent.CreateEventSession, 
			"CREATE_EXTENDED_PROCEDURE" => ServerDdlTriggerEvent.CreateExtendedProcedure, 
			"CREATE_EXTENDED_PROPERTY" => ServerDdlTriggerEvent.CreateExtendedProperty, 
			"CREATE_EXTERNAL_LIBRARY" => ServerDdlTriggerEvent.CreateExternalLibrary, 
			"CREATE_EXTERNAL_RESOURCE_POOL" => ServerDdlTriggerEvent.CreateExternalResourcePool, 
			"CREATE_FULLTEXT_CATALOG" => ServerDdlTriggerEvent.CreateFulltextCatalog, 
			"CREATE_FULLTEXT_INDEX" => ServerDdlTriggerEvent.CreateFulltextIndex, 
			"CREATE_FULLTEXT_STOPLIST" => ServerDdlTriggerEvent.CreateFulltextStoplist, 
			"CREATE_FUNCTION" => ServerDdlTriggerEvent.CreateFunction, 
			"CREATE_INDEX" => ServerDdlTriggerEvent.CreateIndex, 
			"CREATE_LINKED_SERVER" => ServerDdlTriggerEvent.CreateLinkedServer, 
			"CREATE_LINKED_SERVER_LOGIN" => ServerDdlTriggerEvent.CreateLinkedServerLogin, 
			"CREATE_LOGIN" => ServerDdlTriggerEvent.CreateLogin, 
			"CREATE_MASTER_KEY" => ServerDdlTriggerEvent.CreateMasterKey, 
			"CREATE_MESSAGE" => ServerDdlTriggerEvent.CreateMessage, 
			"CREATE_MESSAGE_TYPE" => ServerDdlTriggerEvent.CreateMessageType, 
			"CREATE_PARTITION_FUNCTION" => ServerDdlTriggerEvent.CreatePartitionFunction, 
			"CREATE_PARTITION_SCHEME" => ServerDdlTriggerEvent.CreatePartitionScheme, 
			"CREATE_PLAN_GUIDE" => ServerDdlTriggerEvent.CreatePlanGuide, 
			"CREATE_PROCEDURE" => ServerDdlTriggerEvent.CreateProcedure, 
			"CREATE_QUEUE" => ServerDdlTriggerEvent.CreateQueue, 
			"CREATE_REMOTE_SERVER" => ServerDdlTriggerEvent.CreateRemoteServer, 
			"CREATE_REMOTE_SERVICE_BINDING" => ServerDdlTriggerEvent.CreateRemoteServiceBinding, 
			"CREATE_RESOURCE_POOL" => ServerDdlTriggerEvent.CreateResourcePool, 
			"CREATE_ROLE" => ServerDdlTriggerEvent.CreateRole, 
			"CREATE_ROUTE" => ServerDdlTriggerEvent.CreateRoute, 
			"CREATE_RULE" => ServerDdlTriggerEvent.CreateRule, 
			"CREATE_SCHEMA" => ServerDdlTriggerEvent.CreateSchema, 
			"CREATE_SEARCH_PROPERTY_LIST" => ServerDdlTriggerEvent.CreateSearchPropertyList, 
			"CREATE_SECURITY_POLICY" => ServerDdlTriggerEvent.CreateSecurityPolicy, 
			"CREATE_SEQUENCE" => ServerDdlTriggerEvent.CreateSequence, 
			"CREATE_SERVER_AUDIT" => ServerDdlTriggerEvent.CreateServerAudit, 
			"CREATE_SERVER_AUDIT_SPECIFICATION" => ServerDdlTriggerEvent.CreateServerAuditSpecification, 
			"CREATE_SERVER_ROLE" => ServerDdlTriggerEvent.CreateServerRole, 
			"CREATE_SERVICE" => ServerDdlTriggerEvent.CreateService, 
			"CREATE_SPATIAL_INDEX" => ServerDdlTriggerEvent.CreateSpatialIndex, 
			"CREATE_STATISTICS" => ServerDdlTriggerEvent.CreateStatistics, 
			"CREATE_SYMMETRIC_KEY" => ServerDdlTriggerEvent.CreateSymmetricKey, 
			"CREATE_SYNONYM" => ServerDdlTriggerEvent.CreateSynonym, 
			"CREATE_TABLE" => ServerDdlTriggerEvent.CreateTable, 
			"CREATE_TRIGGER" => ServerDdlTriggerEvent.CreateTrigger, 
			"CREATE_TYPE" => ServerDdlTriggerEvent.CreateType, 
			"CREATE_USER" => ServerDdlTriggerEvent.CreateUser, 
			"CREATE_VIEW" => ServerDdlTriggerEvent.CreateView, 
			"CREATE_WORKLOAD_GROUP" => ServerDdlTriggerEvent.CreateWorkloadGroup, 
			"CREATE_XML_INDEX" => ServerDdlTriggerEvent.CreateXmlIndex, 
			"CREATE_XML_SCHEMA_COLLECTION" => ServerDdlTriggerEvent.CreateXmlSchemaCollection, 
			"DENY_DATABASE" => ServerDdlTriggerEvent.DenyDatabase, 
			"DENY_SERVER" => ServerDdlTriggerEvent.DenyServer, 
			"DROP_APPLICATION_ROLE" => ServerDdlTriggerEvent.DropApplicationRole, 
			"DROP_ASSEMBLY" => ServerDdlTriggerEvent.DropAssembly, 
			"DROP_ASYMMETRIC_KEY" => ServerDdlTriggerEvent.DropAsymmetricKey, 
			"DROP_AUDIT" => ServerDdlTriggerEvent.DropAudit, 
			"DROP_AVAILABILITY_GROUP" => ServerDdlTriggerEvent.DropAvailabilityGroup, 
			"DROP_BROKER_PRIORITY" => ServerDdlTriggerEvent.DropBrokerPriority, 
			"DROP_CERTIFICATE" => ServerDdlTriggerEvent.DropCertificate, 
			"DROP_COLUMN_ENCRYPTION_KEY" => ServerDdlTriggerEvent.DropColumnEncryptionKey, 
			"DROP_COLUMN_MASTER_KEY" => ServerDdlTriggerEvent.DropColumnMasterKey, 
			"DROP_CONTRACT" => ServerDdlTriggerEvent.DropContract, 
			"DROP_CREDENTIAL" => ServerDdlTriggerEvent.DropCredential, 
			"DROP_CRYPTOGRAPHIC_PROVIDER" => ServerDdlTriggerEvent.DropCryptographicProvider, 
			"DROP_DATABASE" => ServerDdlTriggerEvent.DropDatabase, 
			"DROP_DATABASE_AUDIT_SPECIFICATION" => ServerDdlTriggerEvent.DropDatabaseAuditSpecification, 
			"DROP_DATABASE_ENCRYPTION_KEY" => ServerDdlTriggerEvent.DropDatabaseEncryptionKey, 
			"DROP_DEFAULT" => ServerDdlTriggerEvent.DropDefault, 
			"DROP_ENDPOINT" => ServerDdlTriggerEvent.DropEndpoint, 
			"DROP_EVENT_NOTIFICATION" => ServerDdlTriggerEvent.DropEventNotification, 
			"DROP_EVENT_SESSION" => ServerDdlTriggerEvent.DropEventSession, 
			"DROP_EXTENDED_PROCEDURE" => ServerDdlTriggerEvent.DropExtendedProcedure, 
			"DROP_EXTENDED_PROPERTY" => ServerDdlTriggerEvent.DropExtendedProperty, 
			"DROP_EXTERNAL_LIBRARY" => ServerDdlTriggerEvent.DropExternalLibrary, 
			"DROP_EXTERNAL_RESOURCE_POOL" => ServerDdlTriggerEvent.DropExternalResourcePool, 
			"DROP_FULLTEXT_CATALOG" => ServerDdlTriggerEvent.DropFulltextCatalog, 
			"DROP_FULLTEXT_INDEX" => ServerDdlTriggerEvent.DropFulltextIndex, 
			"DROP_FULLTEXT_STOPLIST" => ServerDdlTriggerEvent.DropFulltextStoplist, 
			"DROP_FUNCTION" => ServerDdlTriggerEvent.DropFunction, 
			"DROP_INDEX" => ServerDdlTriggerEvent.DropIndex, 
			"DROP_LINKED_SERVER" => ServerDdlTriggerEvent.DropLinkedServer, 
			"DROP_LINKED_SERVER_LOGIN" => ServerDdlTriggerEvent.DropLinkedServerLogin, 
			"DROP_LOGIN" => ServerDdlTriggerEvent.DropLogin, 
			"DROP_MASTER_KEY" => ServerDdlTriggerEvent.DropMasterKey, 
			"DROP_MESSAGE" => ServerDdlTriggerEvent.DropMessage, 
			"DROP_MESSAGE_TYPE" => ServerDdlTriggerEvent.DropMessageType, 
			"DROP_PARTITION_FUNCTION" => ServerDdlTriggerEvent.DropPartitionFunction, 
			"DROP_PARTITION_SCHEME" => ServerDdlTriggerEvent.DropPartitionScheme, 
			"DROP_PLAN_GUIDE" => ServerDdlTriggerEvent.DropPlanGuide, 
			"DROP_PROCEDURE" => ServerDdlTriggerEvent.DropProcedure, 
			"DROP_QUEUE" => ServerDdlTriggerEvent.DropQueue, 
			"DROP_REMOTE_SERVER" => ServerDdlTriggerEvent.DropRemoteServer, 
			"DROP_REMOTE_SERVICE_BINDING" => ServerDdlTriggerEvent.DropRemoteServiceBinding, 
			"DROP_RESOURCE_POOL" => ServerDdlTriggerEvent.DropResourcePool, 
			"DROP_ROLE" => ServerDdlTriggerEvent.DropRole, 
			"DROP_ROLE_MEMBER" => ServerDdlTriggerEvent.DropRoleMember, 
			"DROP_ROUTE" => ServerDdlTriggerEvent.DropRoute, 
			"DROP_RULE" => ServerDdlTriggerEvent.DropRule, 
			"DROP_SCHEMA" => ServerDdlTriggerEvent.DropSchema, 
			"DROP_SEARCH_PROPERTY_LIST" => ServerDdlTriggerEvent.DropSearchPropertyList, 
			"DROP_SECURITY_POLICY" => ServerDdlTriggerEvent.DropSecurityPolicy, 
			"DROP_SENSITIVITY_CLASSIFICATION" => ServerDdlTriggerEvent.DropSensitivityClassification, 
			"DROP_SEQUENCE" => ServerDdlTriggerEvent.DropSequence, 
			"DROP_SERVER_AUDIT" => ServerDdlTriggerEvent.DropServerAudit, 
			"DROP_SERVER_AUDIT_SPECIFICATION" => ServerDdlTriggerEvent.DropServerAuditSpecification, 
			"DROP_SERVER_ROLE" => ServerDdlTriggerEvent.DropServerRole, 
			"DROP_SERVER_ROLE_MEMBER" => ServerDdlTriggerEvent.DropServerRoleMember, 
			"DROP_SERVICE" => ServerDdlTriggerEvent.DropService, 
			"DROP_SIGNATURE" => ServerDdlTriggerEvent.DropSignature, 
			"DROP_SIGNATURE_SCHEMA_OBJECT" => ServerDdlTriggerEvent.DropSignatureSchemaObject, 
			"DROP_STATISTICS" => ServerDdlTriggerEvent.DropStatistics, 
			"DROP_SYMMETRIC_KEY" => ServerDdlTriggerEvent.DropSymmetricKey, 
			"DROP_SYNONYM" => ServerDdlTriggerEvent.DropSynonym, 
			"DROP_TABLE" => ServerDdlTriggerEvent.DropTable, 
			"DROP_TRIGGER" => ServerDdlTriggerEvent.DropTrigger, 
			"DROP_TYPE" => ServerDdlTriggerEvent.DropType, 
			"DROP_USER" => ServerDdlTriggerEvent.DropUser, 
			"DROP_VIEW" => ServerDdlTriggerEvent.DropView, 
			"DROP_WORKLOAD_GROUP" => ServerDdlTriggerEvent.DropWorkloadGroup, 
			"DROP_XML_SCHEMA_COLLECTION" => ServerDdlTriggerEvent.DropXmlSchemaCollection, 
			"GRANT_DATABASE" => ServerDdlTriggerEvent.GrantDatabase, 
			"GRANT_SERVER" => ServerDdlTriggerEvent.GrantServer, 
			"LOGON" => ServerDdlTriggerEvent.Logon, 
			"RENAME" => ServerDdlTriggerEvent.Rename, 
			"REVOKE_DATABASE" => ServerDdlTriggerEvent.RevokeDatabase, 
			"REVOKE_SERVER" => ServerDdlTriggerEvent.RevokeServer, 
			"UNBIND_DEFAULT" => ServerDdlTriggerEvent.UnbindDefault, 
			"UNBIND_RULE" => ServerDdlTriggerEvent.UnbindRule, 
			"UPDATE_STATISTICS" => ServerDdlTriggerEvent.UpdateStatistics, 
			_ => ServerDdlTriggerEvent.CreateEndpoint, 
		};
	}
}
